### ISSUE TITLE
Support for Fragments Import pattern

### ISSUE THREAD

**Issue by avivey** [ekampf/gql#19]
A useful pattern when doing component-based design is to have each component specify a graphql Fragment it needs for its data, and the data loading interface imports this fragment somehow:

```py
# File butterfly_painter.py
FRAGMENT= '''
fragment Foo on Butterfly {
    wingColor
}
'''

def paint_butterfly(butterfly: Butterfly):
    return f'<img src="/img/wings/{butterfly_color}.png">'
```

```py3
# File workstuff
import butterfly_painter

QUERY= '''
query find_my_things {
    butterflies(size: LARGE) {
        ... butterfly_painter.FRAGMENT
    }
}
''' + butterfly_painter
```

So that if `paint_butterfly` is changed, the piece of the query it needs can me modified in the same file, instead of somewhere else.

This pattern has some issues, but the use-case (localizing data required for a component to the component) is important and we should support some way to handle it.

**Comment by ekampf** [comment]
This would work:
```
QUERY= '''
query find_my_things {
    butterflies(size: LARGE) {
        ... butterfly_painter.FRAGMENT
    }
}
'''
```
